# Generated by Django 4.2.3 on 2023-07-13 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=10)),
                ('unit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('COMPUTER SCIENCES', 'COMPUTER SCIENCES'), ('BIOLOGICAL SCIENCES', 'BIOLOGICAL SCIENCES'), ('CHEMICAL SCIENCES', 'CHEMICAL SCIENCES'), ('MANAGEMENT SCIENCES', 'MANAGEMENT SCIENCES'), ('MASS COMMUNICATION', 'MASS COMMUNICATION'), ('CRIMINOLOGY', 'CRIMINOLOGY'), ('GENERAL STUDIES', 'GENERAL STUDIES')], max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=30)),
                ('courses', models.ManyToManyField(to='Dashboard.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.person')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=30)),
                ('courses', models.ManyToManyField(to='Dashboard.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.person')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.department'),
        ),
    ]
